version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
